services:
  log-viewer:
    image: ${CI_REGISTRY_IMAGE}:${DEPLOY_IMAGE_TAG}
    network_mode: "host"
    volumes:
      - ${LOG_DIR_PATH}:/var/logs
    environment:
      - API_PORT=${API_PORT}
    restart: unless-stopped
